/*
 * Generated by gdbus-codegen 2.59.0 from com.endlessm.Payg1.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "manager-interface.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for com.endlessm.Payg1 */

const GDBusArgInfo epg_payg1_interface__add_code_method_in_args__code_arg =
{
  -1,  /* ref count */
  (gchar *) "code",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const epg_payg1_interface__add_code_method_in_args[] =
{
  &epg_payg1_interface__add_code_method_in_args__code_arg,
  NULL,
};

const GDBusMethodInfo epg_payg1_interface__add_code_method =
{
  -1,  /* ref count */
  (gchar *) "AddCode",
  (GDBusArgInfo **) epg_payg1_interface__add_code_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo epg_payg1_interface__clear_code_method =
{
  -1,  /* ref count */
  (gchar *) "ClearCode",
  NULL,  /* no in args */
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const epg_payg1_interface_methods[] =
{
  &epg_payg1_interface__add_code_method,
  &epg_payg1_interface__clear_code_method,
  NULL,
};

const GDBusSignalInfo epg_payg1_interface__expired_signal =
{
  -1,  /* ref count */
  (gchar *) "Expired",
  NULL,  /* no args */
  NULL,  /* no annotations */
};

const GDBusSignalInfo * const epg_payg1_interface_signals[] =
{
  &epg_payg1_interface__expired_signal,
  NULL,
};

const GDBusPropertyInfo epg_payg1_interface__code_format_property =
{
  -1,  /* ref count */
  (gchar *) "CodeFormat",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo epg_payg1_interface__enabled_property =
{
  -1,  /* ref count */
  (gchar *) "Enabled",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo epg_payg1_interface__expiry_time_property =
{
  -1,  /* ref count */
  (gchar *) "ExpiryTime",
  (gchar *) "t",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo epg_payg1_interface__rate_limit_end_time_property =
{
  -1,  /* ref count */
  (gchar *) "RateLimitEndTime",
  (gchar *) "t",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const epg_payg1_interface_properties[] =
{
  &epg_payg1_interface__code_format_property,
  &epg_payg1_interface__enabled_property,
  &epg_payg1_interface__expiry_time_property,
  &epg_payg1_interface__rate_limit_end_time_property,
  NULL,
};

const GDBusInterfaceInfo epg_payg1_interface =
{
  -1,  /* ref count */
  (gchar *) "com.endlessm.Payg1",
  (GDBusMethodInfo **) epg_payg1_interface_methods,
  (GDBusSignalInfo **) epg_payg1_interface_signals,
  (GDBusPropertyInfo **) epg_payg1_interface_properties,
  NULL,  /* no annotations */
};

/* ------------------------------------------------------------------------ */
/* Definitions for com.endlessm.Payg1.Provisioning */

const GDBusArgInfo epg_payg1_provisioning_interface__provision_method_in_args__provider_arg =
{
  -1,  /* ref count */
  (gchar *) "provider",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo epg_payg1_provisioning_interface__provision_method_in_args__options_arg =
{
  -1,  /* ref count */
  (gchar *) "options",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const epg_payg1_provisioning_interface__provision_method_in_args[] =
{
  &epg_payg1_provisioning_interface__provision_method_in_args__options_arg,
  &epg_payg1_provisioning_interface__provision_method_in_args__provider_arg,
  NULL,
};

const GDBusMethodInfo epg_payg1_provisioning_interface__provision_method =
{
  -1,  /* ref count */
  (gchar *) "Provision",
  (GDBusArgInfo **) epg_payg1_provisioning_interface__provision_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const epg_payg1_provisioning_interface_methods[] =
{
  &epg_payg1_provisioning_interface__provision_method,
  NULL,
};

const GDBusPropertyInfo epg_payg1_provisioning_interface__provider_property =
{
  -1,  /* ref count */
  (gchar *) "Provider",
  (gchar *) "s",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo epg_payg1_provisioning_interface__provisioned_property =
{
  -1,  /* ref count */
  (gchar *) "Provisioned",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const epg_payg1_provisioning_interface_properties[] =
{
  &epg_payg1_provisioning_interface__provider_property,
  &epg_payg1_provisioning_interface__provisioned_property,
  NULL,
};

const GDBusInterfaceInfo epg_payg1_provisioning_interface =
{
  -1,  /* ref count */
  (gchar *) "com.endlessm.Payg1.Provisioning",
  (GDBusMethodInfo **) epg_payg1_provisioning_interface_methods,
  NULL,  /* no signals */
  (GDBusPropertyInfo **) epg_payg1_provisioning_interface_properties,
  NULL,  /* no annotations */
};

