/*
 * Generated by gdbus-codegen 2.59.0 from com.endlessm.Payg1.xml. DO NOT EDIT.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS

extern const GDBusInterfaceInfo epg_payg1_interface;

G_END_DECLS
